
spawn-zone:
  loc1:
    ==: org.bukkit.Location
    world: world
    x: 0
    y: 0
    z: 0
  loc2:
    ==: org.bukkit.Location
    world: world
    x: 0
    y: 0
    z: 0

#Make sure to have here all levels as in BetterTeams config
levels:
  1:
    block-count: 10000
  2:
    block-count: 20000
  3:
    block-count: 30000
  4:
    block-count: 40000
  5:
    block-count: 50000
  6:
    block-count: 60000
  7:
    block-count: 70000
  8:
    block-count: 80000
  9:
    block-count: 90000
  10:
    block-count: 100000


menu-title: "&0Claim menu"

filler:
  material: "GRAY_STAINED_GLASS_PANE"
  name: ""
  slots:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 17
    - 18
    - 26
    - 27
    - 35
    - 36
    - 37
    - 38
    - 39
    - 40
    - 41
    - 42
    - 43
    - 44



buttons:
  save:
    name: "&aSave"
    material: "DIAMOND"
    model-data: 0
    slot: 22
    lore:
      - "&7Click to save claim"

  corner1:
    name: "&bCorner 1"
    material: "CAULDRON"
    model-data: 0
    slot: 20
    # %x%, %y%, %z%
    lore:
      - "&7Corner 1:"
      - "&7x: %x%"
      - "&7y: %y%"
      - "&7z: %z%"
    loc-not-set-lore:
      - "&7Corner 1: &cNot set"


  corner2:
    name: "&bCorner 2"
    material: "CAULDRON"
    model-data: 0
    slot: 24
    # %x%, %y%, %z%
    lore:
      - "&7Corner 2:"
      - "&7x: %x%"
      - "&7y: %y%"
      - "&7z: %z%"
    loc-not-set-lore:
      - "&7Corner 2: &cNot set"

